from unittest import TestCase
from ASD1.lesson07.task07 import *


class TestOrderedList(TestCase):
    def test_compare(self):
        ordered_list = OrderedList(True)
        self.assertEqual(-1, ordered_list.compare(5, 8))
        self.assertEqual(0, ordered_list.compare(9, 9))
        self.assertEqual(1, ordered_list.compare(8, 4))

    def test_clean(self):
        ordered_list = OrderedList(True)
        ordered_list.clean(False)

    def test_add_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        self.assertEqual(1, ordered_list.len())
        ordered_list.add(5)
        self.assertEqual(2, ordered_list.len())
        self.assertEqual(2, self.reverse_len(ordered_list))
        self.assertEqual(5, ordered_list.head.value)
        self.assertEqual(5, ordered_list.tail.prev.value)
        self.assertEqual(9, ordered_list.head.next.value)
        self.assertEqual(9, ordered_list.tail.value)

        ordered_list.add(10)
        self.assertEqual(3, ordered_list.len())
        self.assertEqual(3, self.reverse_len(ordered_list))
        self.assertEqual(5, ordered_list.head.value)
        self.assertEqual(9, ordered_list.tail.prev.value)
        self.assertEqual(9, ordered_list.head.next.value)
        self.assertEqual(10, ordered_list.tail.value)

        ordered_list.add(15)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(5, ordered_list.head.value)
        self.assertEqual(10, ordered_list.tail.prev.value)
        self.assertEqual(9, ordered_list.head.next.value)
        self.assertEqual(15, ordered_list.tail.value)

        ordered_list.add(7)
        self.assertEqual(5, ordered_list.len())
        self.assertEqual(5, self.reverse_len(ordered_list))
        self.assertEqual(5, ordered_list.head.value)
        self.assertEqual(10, ordered_list.tail.prev.value)
        self.assertEqual(7, ordered_list.head.next.value)
        self.assertEqual(9, ordered_list.head.next.next.value)
        self.assertEqual(15, ordered_list.tail.value)

        ordered_list.add(4)
        self.assertEqual(6, ordered_list.len())
        self.assertEqual(6, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(15, ordered_list.tail.value)
        arr = ordered_list.get_all()
        self.assertEqual(4, arr[0].value)
        self.assertEqual(5, arr[1].value)
        self.assertEqual(7, arr[2].value)
        self.assertEqual(9, arr[3].value)
        self.assertEqual(10, arr[4].value)
        self.assertEqual(15, arr[5].value)

    def test_add_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        self.assertEqual(1, ordered_list.len())
        ordered_list.add(5)
        self.assertEqual(2, ordered_list.len())
        self.assertEqual(2, self.reverse_len(ordered_list))
        self.assertEqual(9, ordered_list.head.value)
        self.assertEqual(9, ordered_list.tail.prev.value)
        self.assertEqual(5, ordered_list.head.next.value)
        self.assertEqual(5, ordered_list.tail.value)

        ordered_list.add(10)
        self.assertEqual(3, ordered_list.len())
        self.assertEqual(3, self.reverse_len(ordered_list))
        self.assertEqual(10, ordered_list.head.value)
        self.assertEqual(9, ordered_list.tail.prev.value)
        self.assertEqual(9, ordered_list.head.next.value)
        self.assertEqual(5, ordered_list.tail.value)

        ordered_list.add(15)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(15, ordered_list.head.value)
        self.assertEqual(9, ordered_list.tail.prev.value)
        self.assertEqual(10, ordered_list.head.next.value)
        self.assertEqual(5, ordered_list.tail.value)

        ordered_list.add(7)
        self.assertEqual(5, ordered_list.len())
        self.assertEqual(5, self.reverse_len(ordered_list))
        self.assertEqual(15, ordered_list.head.value)
        self.assertEqual(7, ordered_list.tail.prev.value)
        self.assertEqual(10, ordered_list.head.next.value)
        self.assertEqual(9, ordered_list.head.next.next.value)
        self.assertEqual(5, ordered_list.tail.value)

        ordered_list.add(4)
        self.assertEqual(6, ordered_list.len())
        self.assertEqual(6, self.reverse_len(ordered_list))
        self.assertEqual(15, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)
        arr = ordered_list.get_all()
        self.assertEqual(4, arr[5].value)
        self.assertEqual(5, arr[4].value)
        self.assertEqual(7, arr[3].value)
        self.assertEqual(9, arr[2].value)
        self.assertEqual(10, arr[1].value)
        self.assertEqual(15, arr[0].value)

    def test_find_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        self.assertEqual(9, ordered_list.find(9).value)
        ordered_list.add(4)
        self.assertEqual(4, ordered_list.find(4).value)
        ordered_list.add(5)
        ordered_list.add(10)
        ordered_list.add(15)
        self.assertIsNone(ordered_list.find(18))
        self.assertIsNone(ordered_list.find(1))
        self.assertIsNone(ordered_list.find(8))

    def test_find_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        self.assertEqual(9, ordered_list.find(9).value)
        ordered_list.add(4)
        self.assertEqual(4, ordered_list.find(4).value)
        ordered_list.add(5)
        ordered_list.add(10)
        self.assertEqual(10, ordered_list.find(10).value)
        ordered_list.add(15)
        self.assertEqual(15, ordered_list.find(15).value)
        self.assertIsNone(ordered_list.find(18))
        self.assertIsNone(ordered_list.find(1))
        self.assertIsNone(ordered_list.find(8))

    def test_delete_empty(self):
        ordered_list = OrderedList(True)
        ordered_list.delete(5)

    def test_delete_one(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.delete(9)
        self.assertIsNone(ordered_list.find(9))
        self.assertEqual(0, ordered_list.len())
        self.assertEqual(0, self.reverse_len(ordered_list))
        self.assertIsNone(ordered_list.head)
        self.assertIsNone(ordered_list.tail)

    def test_delete_head_asc_two(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.delete(4)
        self.assertEqual(1, ordered_list.len())
        self.assertEqual(1, self.reverse_len(ordered_list))
        self.assertEqual(9, ordered_list.head.value)
        self.assertEqual(9, ordered_list.tail.value)

    def test_delete_tail_asc_two(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.delete(9)
        self.assertEqual(1, ordered_list.len())
        self.assertEqual(1, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)

    def test_delete_head_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.delete(4)
        self.assertEqual(2, ordered_list.len())
        self.assertEqual(2, self.reverse_len(ordered_list))
        self.assertEqual(7, ordered_list.head.value)
        self.assertEqual(9, ordered_list.tail.value)

    def test_delete_tail_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.delete(9)
        self.assertEqual(2, ordered_list.len())
        self.assertEqual(2, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(7, ordered_list.tail.value)

    def test_delete_not_exists_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(5)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(10, ordered_list.tail.value)

    def test_delete_from_mid_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(7)
        self.assertEqual(3, ordered_list.len())
        self.assertEqual(3, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(10, ordered_list.tail.value)
        self.assertIsNone(ordered_list.find(7))

    def test_delete_one_of_many_head_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(4)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(10, ordered_list.tail.value)

    def test_delete_one_of_many_tail_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(10)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(10)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(10, ordered_list.tail.value)

    def test_delete_one_of_many_asc(self):
        ordered_list = OrderedList(True)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(7)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(10, ordered_list.tail.value)

    def test_delete_head_desc_two(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.delete(9)
        self.assertEqual(1, ordered_list.len())
        self.assertEqual(1, self.reverse_len(ordered_list))
        self.assertEqual(4, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)

    def test_delete_tail_desc_two(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.delete(4)
        self.assertEqual(1, ordered_list.len())
        self.assertEqual(1, self.reverse_len(ordered_list))
        self.assertEqual(9, ordered_list.head.value)
        self.assertEqual(9, ordered_list.tail.value)

    def test_delete_head_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.delete(9)
        self.assertEqual(2, ordered_list.len())
        self.assertEqual(2, self.reverse_len(ordered_list))
        self.assertEqual(7, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)

    def test_delete_tail_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.delete(4)
        self.assertEqual(2, ordered_list.len())
        self.assertEqual(2, self.reverse_len(ordered_list))
        self.assertEqual(9, ordered_list.head.value)
        self.assertEqual(7, ordered_list.tail.value)

    def test_delete_not_exists_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(5)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(10, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)

    def test_delete_from_mid_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(7)
        self.assertEqual(3, ordered_list.len())
        self.assertEqual(3, self.reverse_len(ordered_list))
        self.assertEqual(10, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)
        self.assertIsNone(ordered_list.find(7))

    def test_delete_one_of_many_tail_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(4)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(10, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)

    def test_delete_one_of_many_head_desc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(10)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(10)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(10, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)

    def test_delete_one_of_many_asc(self):
        ordered_list = OrderedList(False)
        ordered_list.add(9)
        ordered_list.add(4)
        ordered_list.add(7)
        ordered_list.add(7)
        ordered_list.add(10)
        ordered_list.delete(7)
        self.assertEqual(4, ordered_list.len())
        self.assertEqual(4, self.reverse_len(ordered_list))
        self.assertEqual(10, ordered_list.head.value)
        self.assertEqual(4, ordered_list.tail.value)

    def test_compare_strings(self):
        ordered_list = OrderedStringList(False)
        self.assertEqual(0, ordered_list.compare(' 10', '10 '))
        self.assertEqual(0, ordered_list.compare('  apple', '   apple'))
        self.assertEqual(-1, ordered_list.compare('apple', ' banana'))
        self.assertEqual(1, ordered_list.compare('banana ', ' apple'))

    def test_find_desc_str(self):
        ordered_list = OrderedList(False)
        ordered_list.add('9')
        self.assertEqual('9', ordered_list.find('9').value)
        ordered_list.add('4')
        self.assertEqual('4', ordered_list.find('4').value)
        ordered_list.add('5')
        ordered_list.add('10')
        self.assertEqual('10', ordered_list.find('10').value)
        ordered_list.add('15')
        self.assertEqual('15', ordered_list.find('15').value)
        arr = ordered_list.get_all()
        self.assertEqual('9', arr[0].value)
        self.assertEqual('5', arr[1].value)
        self.assertEqual('4', arr[2].value)
        self.assertEqual('15', arr[3].value)
        self.assertEqual('10', arr[4].value)
        self.assertEqual(5, ordered_list.len())
        self.assertEqual(5, self.reverse_len(ordered_list))
        self.assertIsNone(ordered_list.find('18'))
        self.assertIsNone(ordered_list.find('1'))
        self.assertIsNone(ordered_list.find('8'))

    def reverse_len(self, ordered_list) -> int:
        node = ordered_list.tail
        cnt = 0
        while node is not None:
            cnt += 1
            node = node.prev
        return cnt


